# Generated by Django 4.2.11 on 2024-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('info', models.TextField(default='', verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
